language: node_js
node_js:
  - "node"
  - "6"
  - "6.1"
env:
  - "NODE_ENV=development API_AUTH_SECRET=somerandomstring DB_SYNC=0 TOKEN_LIFE_MINUTES=2"
  - "NODE_ENV=production API_AUTH_SECRET=somerandomstring DB_SYNC=0 TOKEN_LIFE_MINUTES=2"
