language: node_js
node_js:
  - "node"
  - "6"
  - "6.1"
env:
  - "NODE_ENV=development  DB_NAME=filedepot DB_USER=root DB_PASS=password DB_CONFIG={\"storage\": \"test/test.tmp.sqlite\", \"dialect\": \"sqlite\"} API_AUTH_SECRET=somerandomstring DB_SYNC=0 TOKEN_LIFE_MINUTES=2"
